camel:
  springboot:
    main-run-controller: true
deadLetterHandleNewException: true

cepik:
  webservice:
    connectionTimeout: 50000
    url: https://api.cepik.gov.pl/pojazdy?wojewodztwo={wojewodztwo}&data-od={data}&page={page}&tylko-zarejestrowane=true&pokaz-wszystkie-pola=true

route:
  input: file:/C:/ImportedCars/input/ #Folder imitates MQ Object
  output: file:/C:/ImportedCars/output/ #Folder imitates MQ Object
  error: file:/C:/ImportedCars/output/error/ #Folder imitates MQ Object
  chunkSize: 100
  timeout: 5000